//  What is Go?
 
// Go is a cross-platform, open source programming language
// Go can be used to create high-performance applications
// Go is a fast, statically typed, compiled language known for its simplicity and efficiency
// Go was developed at Google by Robert Griesemer, Rob Pike, and Ken Thompson in 2007
// Go syntax is similar to C++



// What is Go Used For?

// Web development (server-side)
// Developing network-based programs
// Developing cross-platform enterprise applications
// Cloud-native development



// Why Use Go?

// Go is fun and easy to learn
// Go has fast run time and compilation time
// Go supports concurrency
// Go has memory management
// Go works on different platforms (Windows, Mac, Linux, Raspberry Pi, etc.)




package main

import "fmt"

package main{
	fmt.println("Hello")
}


// A Go file consists of the following parts:
// Package declaration
// Import packages
// Functions
// Statements and expression