// // A condition can be either true or false.

// // Go supports the usual comparison operators from mathematics:

// // Less than <
// // Less than or equal <=
// // Greater than >
// // Greater than or equal >=
// // Equal to ==
// // Not equal to !=
// // Additionally, Go supports the usual logical operators:

// // Logical AND &&
// // Logical OR ||
// // Logical NOT !
// // You can use these operators or their combinations to create conditions for different decisions.



// Go has the following conditional statements:

// if
//  else
//  else if
// switch