// Arrays are used to store multiple values of the same type in a single variable, instead of declaring separate variables for each value.



// Arrays are used to store multiple values of the same type in a single variable, instead of declaring separate variables for each value.



// 1 => With the var keyword
// 2 => With the := sign



// 1=> 
// var array_name = [length]datatype{values} 
// here length is defined

or

// var array_name = [...]datatype{values} 
// here length is inferred