// Slices are similar to arrays, but are more powerful and flexible.

// Like arrays, slices are also used to store multiple values of the same type in a single variable.

// However, unlike arrays, the length of a slice can grow and shrink as you see fit


// declare slice in three different ways 

// Using the []datatype{values} format
// Create a slice from an array
// Using the make() function


//  1 => Create a Slice With []datatype{values}

